import { iri } from "@/lib/protocol";
import type { GraphNode } from "@/lib/protocol";
import { REPOS } from "@/lib/fabric/repos";

/**
 * Seed graph: AGenNext describing itself in its own data model.
 *
 * Every node is a schema.org Thing; relationships use schema.org properties
 * (author, founder, isPartOf, about, …) so the graph is valid Linked Data
 * out of the box. References point at minted IRIs via { "@id": ... }.
 */
const ref = (slug: string) => ({ "@id": iri(slug) });

/**
 * The ecosystem the platform is built on — each is a real project AGenNext
 * adopts. Modeled as schema.org SoftwareApplication nodes and surfaced on the
 * /stack landscape view, so the platform documents its own foundations in its
 * own data model.
 */
const STACK: GraphNode[] = [
  {
    "@id": iri("tech-protobuf"),
    "@type": "SoftwareApplication",
    name: "Protocol Buffers",
    applicationCategory: "Protocol",
    description: "The strongly-typed core contract; JSON-LD and gRPC are encodings of the same messages.",
    url: "https://protobuf.dev/",
    sameAs: "https://github.com/protocolbuffers/protobuf",
  },
  {
    "@id": iri("tech-crossplane"),
    "@type": "SoftwareApplication",
    name: "Crossplane",
    applicationCategory: "ControlPlane",
    description: "Composable control plane: the platform is exposed as a declarative AgennextPlatform API.",
    url: "https://www.crossplane.io/",
    sameAs: "https://github.com/crossplane/crossplane",
  },
  {
    "@id": iri("tech-flux"),
    "@type": "SoftwareApplication",
    name: "Flux",
    applicationCategory: "GitOps",
    description: "GitOps continuous delivery; the cluster reconciles to this repository.",
    url: "https://fluxcd.io/",
    sameAs: "https://github.com/fluxcd/flux2",
  },
  {
    "@id": iri("tech-k3s"),
    "@type": "SoftwareApplication",
    name: "k3s",
    applicationCategory: "Kubernetes",
    description: "Lightweight Kubernetes distribution for edge and small-footprint clusters.",
    url: "https://k3s.io/",
    sameAs: "https://github.com/k3s-io/k3s",
  },
  {
    "@id": iri("tech-buildpacks"),
    "@type": "SoftwareApplication",
    name: "Cloud Native Buildpacks",
    applicationCategory: "Build",
    description: "Builds container images from source without a Dockerfile.",
    url: "https://buildpacks.io/",
    sameAs: "https://github.com/buildpacks/pack",
  },
  {
    "@id": iri("tech-artifacthub"),
    "@type": "SoftwareApplication",
    name: "Artifact Hub",
    applicationCategory: "Registry",
    description: "Discovery and distribution of cloud-native packages such as Helm charts.",
    url: "https://artifacthub.io/",
    sameAs: "https://github.com/artifacthub/hub",
  },
  {
    "@id": iri("tech-cloudevents"),
    "@type": "SoftwareApplication",
    name: "CloudEvents",
    applicationCategory: "EventFormat",
    description: "Vendor-neutral event envelope for source events ingested via Numaflow.",
    url: "https://cloudevents.io/",
    sameAs: "https://github.com/cloudevents/spec",
  },
  {
    "@id": iri("tech-schemaorg"),
    "@type": "SoftwareApplication",
    name: "Schema.org",
    applicationCategory: "Vocabulary",
    description: "The shared vocabulary that defines the platform's graph data model.",
    url: "https://schema.org/docs/full.html",
    sameAs: "https://schema.org/",
  },
  {
    "@id": iri("tech-surrealdb"),
    "@type": "SoftwareApplication",
    name: "SurrealDB",
    applicationCategory: "Database",
    description: "Schemaless multi-model store; the production-grade fabric connector.",
    url: "https://surrealdb.com/",
    sameAs: "https://surrealdb.com/learn/fundamentals/schemaless",
  },
  {
    "@id": iri("tech-opentelemetry"),
    "@type": "SoftwareApplication",
    name: "OpenTelemetry",
    applicationCategory: "Observability",
    description: "The telemetry data model for the platform's traces, metrics and logs.",
    url: "https://opentelemetry.io/",
    sameAs: "https://github.com/open-telemetry/community",
  },
  {
    "@id": iri("tech-spiffe"),
    "@type": "SoftwareApplication",
    name: "SPIFFE",
    applicationCategory: "Identity",
    description: "Workload identity standard; every connector is named by a SPIFFE ID.",
    url: "https://spiffe.io/",
    sameAs: "https://github.com/spiffe/spiffe",
  },
  {
    "@id": iri("tech-openfeature"),
    "@type": "SoftwareApplication",
    name: "OpenFeature",
    applicationCategory: "FeatureFlags",
    description: "Vendor-neutral feature-flag API gating connectors and the write path.",
    url: "https://openfeature.dev/",
    sameAs: "https://github.com/open-feature/spec",
  },
  {
    "@id": iri("tech-opencost"),
    "@type": "SoftwareApplication",
    name: "OpenCost",
    applicationCategory: "FinOps",
    description: "Cost allocation model exposed as an OpenMetrics cost gauge.",
    url: "https://www.opencost.io/",
    sameAs: "https://github.com/opencost/opencost",
  },
  {
    "@id": iri("tech-kubeedge"),
    "@type": "SoftwareApplication",
    name: "KubeEdge",
    applicationCategory: "Edge",
    description: "Edge runtime; the container is lightweight enough to run at the edge.",
    url: "https://kubeedge.io/",
    sameAs: "https://github.com/kubeedge/kubeedge",
  },
  {
    "@id": iri("tech-layotto"),
    "@type": "SoftwareApplication",
    name: "Layotto",
    applicationCategory: "Runtime",
    description: "Multi-runtime application primitives that inspire the connector abstraction.",
    url: "https://mosn.io/layotto/",
    sameAs: "https://github.com/mosn/layotto",
  },
  {
    "@id": iri("tech-hertzbeat"),
    "@type": "SoftwareApplication",
    name: "HertzBeat",
    applicationCategory: "Monitoring",
    description: "Real-time monitoring that scrapes the platform's OpenMetrics endpoint.",
    url: "https://hertzbeat.apache.org/",
    sameAs: "https://landscape.cncf.io/",
  },
  {
    "@id": iri("tech-forgejo"),
    "@type": "SoftwareApplication",
    name: "Forgejo",
    applicationCategory: "DevOps",
    description: "Self-hostable git forge reflecting the platform's open, self-hosted ethos.",
    url: "https://forgejo.org/",
    sameAs: "https://forgejo.org/",
  },
  {
    "@id": iri("tech-wasmcloud"),
    "@type": "SoftwareApplication",
    name: "wasmCloud",
    applicationCategory: "Runtime",
    description: "WebAssembly application platform; portable, sandboxed runtime for connectors at the edge.",
    url: "https://wasmcloud.com/",
    sameAs: "https://github.com/wasmCloud/wasmCloud",
  },
  {
    "@id": iri("tech-instructor"),
    "@type": "SoftwareApplication",
    name: "Instructor",
    applicationCategory: "MachineLearning",
    description: "Structured LLM outputs; extracts typed Schema.org nodes from unstructured sources.",
    url: "https://python.useinstructor.com/",
    sameAs: "https://github.com/567-labs/instructor",
  },
  {
    "@id": iri("tech-numaflow"),
    "@type": "SoftwareApplication",
    name: "Numaflow",
    applicationCategory: "StreamProcessing",
    description: "Kubernetes-native stream processing for ingesting source events into the fabric.",
    url: "https://numaflow.numaproj.io/",
    sameAs: "https://github.com/numaproj/numaflow",
  },
  {
    "@id": iri("tech-kgateway"),
    "@type": "SoftwareApplication",
    name: "kgateway",
    applicationCategory: "Networking",
    description: "Envoy-based cloud-native API and AI gateway fronting the platform's endpoints.",
    url: "https://kgateway.dev/",
    sameAs: "https://github.com/kgateway-dev/kgateway",
  },
  {
    "@id": iri("tech-cubesandbox"),
    "@type": "SoftwareApplication",
    name: "CubeSandbox",
    applicationCategory: "Runtime",
    description: "Cloud-native sandboxing runtime for isolating untrusted connector workloads.",
    url: "https://github.com/TencentCloud/CubeSandbox",
    sameAs: "https://github.com/TencentCloud/CubeSandbox",
  },
  {
    "@id": iri("tech-crio"),
    "@type": "SoftwareApplication",
    name: "CRI-O",
    applicationCategory: "Runtime",
    description: "Lightweight OCI container runtime for Kubernetes; runs the platform's pods.",
    url: "https://cri-o.io/",
    sameAs: "https://github.com/cri-o/cri-o",
  },
  {
    "@id": iri("tech-nccl"),
    "@type": "SoftwareApplication",
    name: "NCCL",
    applicationCategory: "MachineLearning",
    description: "GPU collective communication for distributed training of graph-enrichment models.",
    url: "https://developer.nvidia.com/nccl",
    sameAs: "https://github.com/NVIDIA/nccl",
  },
  {
    "@id": iri("tech-triton"),
    "@type": "SoftwareApplication",
    name: "Triton",
    applicationCategory: "MachineLearning",
    description: "GPU kernel language for high-performance compute behind model inference.",
    url: "https://triton-lang.org/",
    sameAs: "https://github.com/triton-lang/triton",
  },
  {
    "@id": iri("tech-cni"),
    "@type": "SoftwareApplication",
    name: "CNI",
    applicationCategory: "Networking",
    description: "Container Network Interface — the networking standard for the platform's pods.",
    url: "https://www.cni.dev/",
    sameAs: "https://github.com/containernetworking/cni",
  },
  {
    "@id": iri("tech-modelpack"),
    "@type": "SoftwareApplication",
    name: "ModelPack",
    applicationCategory: "MachineLearning",
    description: "OCI-based model packaging spec for distributing AI models as standard artifacts.",
    url: "https://github.com/modelpack/model-spec",
    sameAs: "https://github.com/modelpack/model-spec",
  },
  {
    "@id": iri("tech-permify"),
    "@type": "SoftwareApplication",
    name: "Permify",
    applicationCategory: "Authorization",
    description: "Relationship-based access control (Zanzibar-style) — a natural fit over the graph.",
    url: "https://permify.co/",
    sameAs: "https://github.com/Permify/permify",
  },
  {
    "@id": iri("tech-minder"),
    "@type": "SoftwareApplication",
    name: "Minder",
    applicationCategory: "Security",
    description: "Open software supply-chain security: policy and attestation across repositories.",
    url: "https://mindersec.github.io/",
    sameAs: "https://github.com/mindersec/minder",
  },
  {
    "@id": iri("tech-influxdb"),
    "@type": "SoftwareApplication",
    name: "InfluxDB",
    applicationCategory: "Database",
    description: "Open time-series database for retaining the platform's metrics and traces.",
    url: "https://www.influxdata.com/",
    sameAs: "https://github.com/influxdata/influxdb",
  },
  {
    "@id": iri("tech-kubeflow"),
    "@type": "SoftwareApplication",
    name: "Kubeflow Pipelines",
    applicationCategory: "MachineLearning",
    description: "Open ML workflow orchestration for enrichment pipelines over the graph.",
    url: "https://www.kubeflow.org/docs/components/pipelines/",
    sameAs: "https://github.com/kubeflow/pipelines",
  },
  {
    "@id": iri("tech-mlrun"),
    "@type": "SoftwareApplication",
    name: "MLRun",
    applicationCategory: "MachineLearning",
    description: "Open MLOps framework to operationalize models that classify and link nodes.",
    url: "https://www.mlrun.org/",
    sameAs: "https://github.com/mlrun/mlrun",
  },
  {
    "@id": iri("tech-ai-platform"),
    "@type": "SoftwareApplication",
    name: "AI Platform",
    applicationCategory: "MachineLearning",
    description: "Model serving for enriching and classifying graph nodes (DataRobot-style).",
    url: "https://www.datarobot.com/product/ai-platform/",
    sameAs: "https://www.datarobot.com/",
  },
];

/**
 * Agent building blocks: the composable pieces agents are assembled from —
 * Templates (blueprints), Skills (capabilities), Tools (callable endpoints),
 * and Knowledge (sources). Modeled as schema.org nodes tagged with an
 * applicationCategory, and wired together with hasPart edges.
 */
const BLOCKS: GraphNode[] = [
  // Templates
  {
    "@id": iri("template-research-assistant"),
    "@type": "SoftwareApplication",
    applicationCategory: "AgentTemplate",
    name: "Research Assistant Template",
    description: "Blueprint for an agent that explores the graph and writes briefs.",
    author: ref("agennext"),
    hasPart: [ref("skill-graph-traversal"), ref("skill-summarization"), ref("tool-fabric-query"), ref("knowledge-graph")],
  },
  {
    "@id": iri("template-ops-copilot"),
    "@type": "SoftwareApplication",
    applicationCategory: "AgentTemplate",
    name: "Ops Copilot Template",
    description: "Blueprint for an agent that audits health and control-plane state.",
    author: ref("agennext"),
    hasPart: [ref("skill-health-audit"), ref("tool-metrics"), ref("tool-control")],
  },
  {
    "@id": iri("template-rag-agent"),
    "@type": "SoftwareApplication",
    applicationCategory: "AgentTemplate",
    name: "RAG Agent Template",
    description: "Blueprint for retrieval-augmented agents over the Schema.org knowledge.",
    author: ref("agennext"),
    hasPart: [ref("skill-entity-extraction"), ref("tool-ai-extract"), ref("knowledge-schemaorg")],
  },
  // Skills
  { "@id": iri("skill-graph-traversal"), "@type": "SoftwareApplication", applicationCategory: "Skill", name: "Graph Traversal", description: "Walk neighborhoods and rank related entities." },
  { "@id": iri("skill-summarization"), "@type": "SoftwareApplication", applicationCategory: "Skill", name: "Summarization", description: "Condense a subgraph into a brief." },
  { "@id": iri("skill-entity-extraction"), "@type": "SoftwareApplication", applicationCategory: "Skill", name: "Entity Extraction", description: "Turn text into typed schema.org nodes." },
  { "@id": iri("skill-shortest-path"), "@type": "SoftwareApplication", applicationCategory: "Skill", name: "Shortest-Path Routing", description: "Find the route between two entities." },
  { "@id": iri("skill-health-audit"), "@type": "SoftwareApplication", applicationCategory: "Skill", name: "Health Audit", description: "Assess connectors, flags, and reconciliation state." },
  // Tools (real platform endpoints)
  { "@id": iri("tool-fabric-query"), "@type": "SoftwareApplication", applicationCategory: "Tool", name: "Fabric Query", description: "Query the graph via /api/graph.", url: "https://agennext.com/api/graph" },
  { "@id": iri("tool-path-finder"), "@type": "SoftwareApplication", applicationCategory: "Tool", name: "Path Finder", description: "Shortest route via /api/path.", url: "https://agennext.com/api/path" },
  { "@id": iri("tool-metrics"), "@type": "SoftwareApplication", applicationCategory: "Tool", name: "Metrics", description: "OpenMetrics via /api/metrics.", url: "https://agennext.com/api/metrics" },
  { "@id": iri("tool-ai-extract"), "@type": "SoftwareApplication", applicationCategory: "Tool", name: "AI Extract", description: "Text → nodes via /api/extract.", url: "https://agennext.com/api/extract" },
  { "@id": iri("tool-control"), "@type": "SoftwareApplication", applicationCategory: "Tool", name: "Control", description: "Desired/observed state via /api/control.", url: "https://agennext.com/api/control" },
  // Knowledge
  { "@id": iri("knowledge-schemaorg"), "@type": "Dataset", applicationCategory: "Knowledge", name: "Schema.org Meta-Model", description: "The full schema.org vocabulary backing the type system.", isBasedOn: "https://schema.org/docs/full.html" },
  { "@id": iri("knowledge-graph"), "@type": "Dataset", applicationCategory: "Knowledge", name: "AGenNext Knowledge Graph", description: "The unified Schema.org instance graph.", creator: ref("agennext") },
];

export const SEED: GraphNode[] = [
  {
    "@id": iri("agennext"),
    "@type": "Organization",
    name: "AGenNext",
    legalName: "AGenNext",
    description:
      "An open, protocol-first platform for building a cloud-native data fabric over a Schema.org knowledge graph.",
    url: "https://agennext.com",
    founder: ref("founder"),
    sameAs: ["https://schema.org/Organization"],
    knowsAbout: [ref("term-cloud-native"), ref("term-linked-data")],
  },
  {
    "@id": iri("founder"),
    "@type": "Person",
    name: "AGenNext Maintainers",
    description: "The maintainers stewarding the AGenNext platform and protocol.",
    worksFor: ref("agennext"),
  },
  {
    "@id": iri("platform"),
    "@type": ["SoftwareApplication", "CreativeWork"],
    name: "AGenNext Platform",
    applicationCategory: "DeveloperApplication",
    operatingSystem: "Cloud-native (container)",
    description:
      "The UI + API surface that exposes the data fabric as protocol responses and as browsable, Linked-Data HTML.",
    author: ref("agennext"),
    isPartOf: ref("website"),
    about: ref("graph"),
    isBasedOn: [
      ref("tech-protobuf"),
      ref("tech-crossplane"),
      ref("tech-flux"),
      ref("tech-k3s"),
      ref("tech-buildpacks"),
      ref("tech-artifacthub"),
      ref("tech-cloudevents"),
      ref("tech-schemaorg"),
      ref("tech-surrealdb"),
      ref("tech-opentelemetry"),
      ref("tech-spiffe"),
      ref("tech-openfeature"),
      ref("tech-opencost"),
      ref("tech-kubeedge"),
      ref("tech-layotto"),
      ref("tech-hertzbeat"),
      ref("tech-forgejo"),
      ref("tech-wasmcloud"),
      ref("tech-kubeflow"),
      ref("tech-mlrun"),
      ref("tech-influxdb"),
      ref("tech-minder"),
      ref("tech-permify"),
      ref("tech-modelpack"),
      ref("tech-cni"),
      ref("tech-crio"),
      ref("tech-nccl"),
      ref("tech-triton"),
      ref("tech-cubesandbox"),
      ref("tech-kgateway"),
      ref("tech-numaflow"),
      ref("tech-instructor"),
    ],
  },
  {
    "@id": iri("protocol"),
    "@type": "TechArticle",
    name: "AGenNext Protocol 1.0",
    headline: "A JSON-LD wire protocol for a Schema.org data fabric",
    description:
      "Protocol-first specification: the JSON-LD context, node and query shapes, and the response envelope shared by every boundary.",
    author: ref("agennext"),
    about: ref("graph"),
    isBasedOn: ["https://schema.org/", "https://www.w3.org/TR/json-ld11/"],
  },
  {
    "@id": iri("fabric"),
    "@type": ["SoftwareSourceCode", "SoftwareApplication"],
    name: "AGenNext Data Fabric",
    programmingLanguage: "TypeScript",
    description:
      "A schemaless connector layer that unifies many sources into one Schema.org graph. Ships in-memory and SurrealDB-compatible connectors.",
    author: ref("agennext"),
    isPartOf: ref("platform"),
    about: ref("graph"),
  },
  {
    "@id": iri("graph"),
    "@type": "Dataset",
    name: "AGenNext Knowledge Graph",
    description:
      "The unified Schema.org graph: nodes are Things, edges are schema.org properties, serialized as JSON-LD.",
    creator: ref("agennext"),
    isBasedOn: "https://schema.org/docs/full.html",
    license: "https://creativecommons.org/licenses/by/4.0/",
  },
  {
    "@id": iri("website"),
    "@type": "WebSite",
    name: "agennext.com",
    url: "https://agennext.com",
    description: "The AGenNext platform on the web.",
    publisher: ref("agennext"),
    about: ref("graph"),
  },
  {
    "@id": iri("observability"),
    "@type": "SoftwareApplication",
    name: "AGenNext Observability",
    applicationCategory: "Monitoring",
    description:
      "OpenTelemetry-shaped traces, metrics and structured logs, exposed in OpenMetrics format for collectors such as HertzBeat.",
    isPartOf: ref("platform"),
    isBasedOn: ["https://opentelemetry.io/", "https://openmetrics.io/"],
  },
  {
    "@id": iri("term-cloud-native"),
    "@type": "DefinedTerm",
    name: "Cloud Native",
    description:
      "Containerized, dynamically orchestrated, 12-factor software aligned with the CNCF landscape.",
    url: "https://landscape.cncf.io/",
    inDefinedTermSet: "https://www.cncf.io/",
  },
  {
    "@id": iri("term-linked-data"),
    "@type": "DefinedTerm",
    name: "Linked Data",
    description:
      "Structured data published as JSON-LD using shared vocabularies so machines can follow relationships across documents.",
    url: "https://www.w3.org/standards/semanticweb/data",
  },
  {
    "@id": iri("agent-core"),
    "@type": ["SoftwareApplication"],
    name: "AgentCore",
    applicationCategory: "Agent",
    description:
      "The agent runtime: registers, describes, and dispatches the platform's agents over the data fabric.",
    author: ref("agennext"),
    isPartOf: ref("platform"),
    about: ref("graph"),
  },
  {
    "@id": iri("agent-research"),
    "@type": ["SoftwareApplication"],
    name: "Research Agent",
    applicationCategory: "Agent",
    description:
      "An agent that works over the data fabric: explores the graph around a subject, finds routes to key hubs, and writes a cited research brief.",
    author: ref("agennext"),
    isPartOf: ref("platform"),
    about: ref("graph"),
    isBasedOn: ref("template-research-assistant"),
  },
  {
    "@id": iri("agent-operations"),
    "@type": ["SoftwareApplication"],
    name: "Operations Agent",
    applicationCategory: "Agent",
    description:
      "Audits connector health, control-plane state, and feature flags, then reports findings and recommendations.",
    author: ref("agennext"),
    isPartOf: ref("platform"),
    about: ref("observability"),
    isBasedOn: ref("template-ops-copilot"),
  },
  {
    "@id": iri("agent-k8s"),
    "@type": ["SoftwareApplication"],
    name: "Kubernetes Agent",
    applicationCategory: "Agent",
    description:
      "Describes the intended Kubernetes topology from the control-plane spec and flags deployment risks.",
    author: ref("agennext"),
    isPartOf: ref("platform"),
    about: ref("term-cloud-native"),
  },
  ...BLOCKS,
  ...STACK,
  ...REPOS,
];
